name: Run Hello World Action
on:
  workflow_dispatch:
    inputs:
      name-person:
        description: 'Nombre de la persona a saludar'
        required: true
        type: string

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Necesario para acceder a la acción local
        with:
          fetch-depth: 0          

      - name: Hello world action step
        id: hello
        uses: ./actions/hello-world
        with:
          who-to-greet: ${{ inputs.name-person }}

      - name: Sample Api URL
        run: |
          echo "ApiUrl - ${{ github.api_url }}"
          echo "OS - $RUNNER_OS"
      
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: Hello world composite action step
        id: hello-composite
        uses: ./actions/hello-world-composite
        with:
          who-to-greet: ${{ inputs.name-person }}
          
      - name: print random number
        run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.hello-composite.outputs.random-number }}
          
  another_hello_world_job:
    runs-on: ubuntu-latest
    name: another_hello_world_job
    steps:
      - name: Set output
        id: another_hello_world_job_step1
        run: echo "my_var=my variable" >> $GITHUB_OUTPUT
        
      - name: Print output
        id: another_hello_world_job_step2
        run: echo "El valor es ${{ steps.another_hello_world_job_step1.outputs.my_var }}"
