name: Sample Service Container
on:
  workflow_dispatch:

concurrency:
  group: sample_service_container
  cancel-in-progress: true

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages  # Ruta de caché
  
jobs:
  setup-execute-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
       image: mysql:8.0
       env:
        MYSQL_ROOT_PASSWORD: root_test
        MYSQL_DATABASE: testdb
       ports:
        - 3306:3306
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for Mysql to be healty
        run: |
          echo "Waiting for MySQL..."
          sleep 30s
        shell: bash

#      - name: Import database schema
#        run: |
#          mysql -h 127.0.0.1 -u root_test -p rootpassword testdb < database/schema.sql

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        id: cache-nuget
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
          
      - name: Restore dependencies
        run: dotnet restore src/HSoft.SampleActions.ConsoleApp.sln --packages ${{ env.NUGET_PACKAGES }}

      - name: Build
        run: dotnet build src/HSoft.SampleActions.ConsoleApp.sln --no-restore

      - name: Run integration tests
        run: dotnet test src/HSoft.SampleActions.ConsoleApp.sln --filter Category=Integration
